#!/bin/sh

mkdir -p ~/.PS2E ~/.pcsx2/bios
cd ~/.pcsx2
ln -snf %GAMES_DATADIR%/pcsx2/* .
ln -snf %GAMES_DATADIR%/pcsx2/.pixmaps
ln -snf %GAMES_LIBDIR%/ps2emu/plugins
ln -snf plugins/cfg
ln -snf ../.PS2E inis
exec %GAMES_BINDIR%/pcsx2.bin ${@}
